version: '3.3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8084:80"    
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
